### ISSUE TITLE
influxdb driver loses a lot of packages

### ISSUE THREAD

**Issue by ezotrank** [ezotrank/logsend#4]
- write regression tests

**Comment by dimafujitsu** [comment]
influxdb has new api. require update
https://github.com/influxdb/influxdb/commit/44d43462cfda8759f2571957a993242ee8abe7c7

**Comment by ezotrank** [comment]
Yes, I have known. In 0.9 version api changed without backward capability and they rewrite this piece of code every time. I known the time when influxdb/client was a separate project. I'm thinking about write own influxdb client.
